# rustup toolchain install nightly
# cargo +nightly run --release

# Fastest templating options: askama, horrowshow, maud

[package]
name = "lemmy-lite"
version = "0.1.0"
authors = ["Iron Oxidizer"]
edition = "2018"

[dependencies]
actix-web = "*"
serde = "*"
maud = { version = "*", features = ["actix-web"] } 
reqwest = { version = "*", features = ["json"] }
tokio = { version = "*", features = ["full"] }
