[package]
name = "lemmy-lite"
version = "0.1.0"
authors = ["Iron Oxidizer"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "2.0.0", features=["rustls"] }
rustls = "0.17.0"
serde = "1.0.111"
maud = { version = "0.22.0", features = ["actix-web"] }
