# rustup toolchain install nightly
# cargo +nightly run --release

# Fastest templating options: askama, horrowshow, maud

[package]
name = "lemmy-lite"
version = "0.1.0"
authors = ["Iron Oxidizer"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
serde = "1.0.111"
maud = { git="https://github.com/lambda-fairy/maud", features = ["actix-web"] }
